- name: Update repositories cache
  apt: update_cache=yes

- name: Install nginx & php packages
  apt: name={{ item }} state=present
  with_items:
    - nginx
    - nginx-extras
    - php5-fpm
    - php5-mysql

- name: Remove default virtual host
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy nginx vhost to /etc/nginx/sites-available
  template:
    src: wordpress.conf.j2
    dest: /etc/nginx/sites-available/wordpress.conf
    owner: root
    group: root
    mode: 0644

- name: Enable wordpress virtual host
  file:
    src: /etc/nginx/sites-available/wordpress.conf
    dest: /etc/nginx/sites-enabled/wordpress.conf
    state: link
