# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-14.04"
  config.vm.hostname = "wp-test"
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: 'ssh'
  config.ssh.port = 2222
  config.ssh.insert_key = false

  # port forward nginx
  config.vm.network :forwarded_port, guest: 80,   host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "10.10.10.22"

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  config.ssh.forward_agent = true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  config.vm.synced_folder ".", "/wordpress",          disabled: false, type: "nfs"


  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    # vb.gui = true

    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory",  "1024"]
    vb.customize ["modifyvm", :id, "--acpi",    "on"]
    vb.customize ["modifyvm", :id, "--ioapic",  "on"]
    vb.customize ["modifyvm", :id, "--cpus",  "1"]
  end

  #config.vm.provision :shell, path: 'scripts/vm_provision.sh'
  config.vm.provision "ansible" do |ansible|
    ansible.host_key_checking = false
    ansible.playbook = "wordpress.yml"
    ansible.limit = "all"
    ansible.inventory_path = "hosts"
    ansible.verbose = 'vv'
  end

end
