- name: Install MySQL packages
  apt: name={{ item }} state=present force=yes
  with_items:
    - mysql-server
    - python-mysqldb

- name: Create .my.cnf for setting mysql root password
  local_action:
    module: lineinfile
    path: ~/.my.cnf
    state: present
    line: '{{ item }}'
  with_items:
    - '[client]'
    - 'user=root'
    - 'password='

- name: Add drupal database
  mysql_db:
    name: drupal
    state: present

- name: Add new user
  mysql_user:
    name: drupal
    password: drupal12345
    priv: '*.*:ALL'
    state: present
