- name: Download latest drupal from internet
  get_url:
    url: https://ftp.drupal.org/files/projects/drupal-{{ version }}.tar.gz 
    dest: /tmp/drupal.tar.gz
    mode: 0644

- name: Create directory /var/www
  file:
    path: /var/www
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Install targz packages
  apt: name={{ item }} state=present
  with_items:
    - tar
    - gzip

- name: Extract drupal
  unarchive:
    src: /tmp/drupal.tar.gz
    dest: /var/www
    remote_src: True
    owner: www-data
    group: www-data
    mode: 0755
  notify: restart nginx
